services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "8088:15672"
      - "15672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
