<?php

/**
 * This file is @generated by AsyncAPI PHP Generator. Do not edit it manually.
 */

namespace Siemendev\AsyncapiPhp\Demo\Stub;

class TestMessage extends \Siemendev\AsyncapiPhp\Message\AbstractMessage
{
    private string $name;
    private ?int $age;

    public static function getMessageName(): string
    {
        return 'test';
    }

    public function __construct(string $name, ?int $age = null)
    {
        $this->name = $name;
        $this->age = $age;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(?int $age): self
    {
        $this->age = $age;

        return $this;
    }
}
