name: "Adapters: AMQP"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --working-dir=adapters/amqp

    - name: Run PHPStan
      run: |
        cd adapters/amqp
        if [ ! -f vendor/bin/phpstan ]; then
          composer require --dev phpstan/phpstan
        fi
        vendor/bin/phpstan analyse

  functional-tests:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:4-alpine
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --working-dir=adapters/amqp

    - name: Run functional tests
      run: |
        cd adapters/amqp
        php vendor/bin/phpunit --configuration phpunit.xml --colors=always
  cs-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --working-dir=adapters/amqp

    - name: Run PHP CS Fixer
      run: |
        cd adapters/amqp
        if [ ! -f vendor/bin/php-cs-fixer ]; then
          composer require --dev friendsofphp/php-cs-fixer
        fi
        PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --config=../../.php-cs-fixer.php --dry-run --diff --no-interaction --ansi
